version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sih-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/sih_db
    networks:
      - sih-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sih-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - sih-net

networks:
  sih-net:
    driver: bridge